### ISSUE TITLE
Maintained

### ISSUE THREAD

**Issue by konstantinmds** [jsnee/vscode-azkeyvault-helper#3]
Hi, the extension i installed from vscode seems broken ? 

Is this still actively maintained library ?

**Comment by jsnee** [comment]
I'm not actively adding any new features, but if there happen to be any bugs I will see to fix them. Could you elaborate on how this extension is behaving for you? You installed the Azure CLI and ran the login command?

**Comment by konstantinmds** [comment]
After login from azure CLI, i refresh the window, but nothing happens inside the vscode window, no elements inside the vscode Tree

**Comment by jsnee** [comment]
Did you add the name of your Azure KeyVaults to the VSCode setting `azkeyvaulthelper.keyvaults`?

**Comment by konstantinmds** [comment]
Thank you, i thought that extension would activate `azkeyvaulthelper.keyvaults` through the command pallete, so i tried like that.

All works fine.

**Comment by jsnee** [comment]
Sounds good! Glad I can help!
